// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Web
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        // ✅ SOLUÇÃO: Linux usa config Web
        return web;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Pnr0XKqMMzFVRz_pEYY4RJ5NteC6YhM',
    appId: '1:480421139178:web:128a71913bf0bc5f443d93',
    messagingSenderId: '480421139178',
    projectId: 'patrimonio-ia-samara',
    authDomain: 'patrimonio-ia-samara.firebaseapp.com',
    storageBucket: 'patrimonio-ia-samara.firebasestorage.app',
    measurementId: 'G-PES07HM7ER',
  );

  // ===================== WEB =====================

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlR3uFWrCnvIysF2AGQhn-UXLMoOLtmg',
    appId: '1:480421139178:android:a2b1d219e5983564443d93',
    messagingSenderId: '480421139178',
    projectId: 'patrimonio-ia-samara',
    storageBucket: 'patrimonio-ia-samara.firebasestorage.app',
  );

  // ===================== ANDROID =====================

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_7OAH4nCrilqFTBXwV7ISZ5EeciXDOj8',
    appId: '1:480421139178:ios:ec74ae623ca91ec6443d93',
    messagingSenderId: '480421139178',
    projectId: 'patrimonio-ia-samara',
    storageBucket: 'patrimonio-ia-samara.firebasestorage.app',
    iosBundleId: 'br.com.seunome.patrimonioIa',
  );

  // ===================== IOS =====================

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_7OAH4nCrilqFTBXwV7ISZ5EeciXDOj8',
    appId: '1:480421139178:ios:ec74ae623ca91ec6443d93',
    messagingSenderId: '480421139178',
    projectId: 'patrimonio-ia-samara',
    storageBucket: 'patrimonio-ia-samara.firebasestorage.app',
    iosBundleId: 'br.com.seunome.patrimonioIa',
  );

  // ===================== MACOS =====================

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Pnr0XKqMMzFVRz_pEYY4RJ5NteC6YhM',
    appId: '1:480421139178:web:7c00b9a2cc392925443d93',
    messagingSenderId: '480421139178',
    projectId: 'patrimonio-ia-samara',
    authDomain: 'patrimonio-ia-samara.firebaseapp.com',
    storageBucket: 'patrimonio-ia-samara.firebasestorage.app',
    measurementId: 'G-LDTMZY8MTZ',
  );

  // ===================== WINDOWS =====================
}